name: Playwright Tests
on:
  push:
    branches: [ develop, 'releases/**' ]
  pull_request:
    branches: [ develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    container: mcr.microsoft.com/playwright:v1.52.0-noble
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      run: HOME=/root npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
